name = "Git Cliff"
description = "A tool to generate changelogs from git metadata using conventional commits."
kickstart_version = 1
authors = ["Sheape"]
keywords = ["git", "changelog", "conventional commits", "release notes"]

[[variables]]
name = "github_user"
default = "Sheape"
prompt = "What is your GitHub username/organization?"

[[variables]]
name = "repo_name"
default = "repo"
prompt = "What is the name of your repository (both local and remote)?"
